#262 [feat] koltin entity 작성 및 멀티 모듈 도입
ASAP-as-soon-as-possible/ASAP_Server pull request #263
Opened 2024-06-20 02:15 UTC by sohyundoh

## ✒️ 관련 이슈번호
- Closes #262 

## Key Changes 🔑
1. exception을 common 모듈에 입력했는데 확인해보니 아래와 같은 Exception이 있더라고요 (예외 상황에도 데이터를 담아보내야 하는 케이스 때문에) 모듈간 의존성 문제 때문에 잠시 보류했습니다!
![image](https://github.com/ASAP-as-soon-as-possible/ASAP_Server/assets/79795051/9319f688-c15a-4298-b82d-a45e3b113759)
2. `TimeBlock`에 `TimeBlockUser` List로 받아오던 부분에서 kotlin의 List는 읽기만 가능하기 때문에 MutableList로 변경하였습니다!

## To Reviewers 📢
- 도메인 작업하다가 생각이 들었는데 저희 JpaAuditingClass도 해야합니다!

2024-06-20 02:35 UTC, KWY0218 commented
@sohyundoh 

> 그리고 예외 클래스에서 아래와 같이 상속받을 때 변수 오버라이딩을 했는데욥..! val 선언을 안하는 경우 오버라이딩 하지 않아도 되는데 어떤 방식이 맞는지 몰라 우선 올립니다!

기존 코드를 보면 아규먼트로 error 를 받아 지역변수로 저장한 다음에 사용하고 있습니다.
kotlin에서는 매개변수에 val을 선언하는 것은 자바로 따지면 final val를 생성한다는 것과 일치합니다.
| 코틀린 코드 | 디컴파일 코드 |
| --- | --- |
| ![image](https://github.com/ASAP-as-soon-as-possible/ASAP_Server/assets/82709044/d590ecfd-cdfc-4bba-9e87-81f5a35ff3e8) | ![image](https://github.com/ASAP-as-soon-as-possible/ASAP_Server/assets/82709044/cb7f8762-64b3-40b9-adb9-cf609d8c8086) |

실제로 코틀린을 디컴파일하면 위처럼 됩니다. 기존 코드와 유사하게 되죠??
따라서 오버라이딩하는 방식이 맞습니다!!

2024-06-20 02:35 UTC, KWY0218 commented
> 도메인 작업하다가 생각이 들었는데 저희 JpaAuditingClass도 해야합니다!
도메인 작업할 때 깜박한 거 같네요..! 혹시 이거까지 반영해주실 수 있을까요?!

2024-06-20 02:37 UTC, KWY0218 commented
> exception을 common 모듈에 입력했는데 확인해보니 아래와 같은 Exception이 있더라고요 (예외 상황에도 데이터를 담아보내야 하는 케이스 때문에) 모듈간 의존성 문제 때문에 잠시 보류했습니다!

흠.. 그러면 String 으로 data message 값을 받는 것은 어떨까요?
이러한 경우 같으면 이제 비즈니스 단에서 **객체를 toString해서 전달**한다면 기존의 방식을 유지할 수 있을 것이라 생각합니다..!
어떻게 생각하시나요?

2024-06-20 02:42 UTC, sohyundoh commented
> > exception을 common 모듈에 입력했는데 확인해보니 아래와 같은 Exception이 있더라고요 (예외 상황에도 데이터를 담아보내야 하는 케이스 때문에) 모듈간 의존성 문제 때문에 잠시 보류했습니다!
> 
> 흠.. 그러면 String 으로 data message 값을 받는 것은 어떨까요? 이러한 경우 같으면 이제 비즈니스 단에서 **객체를 toString해서 전달**한다면 기존의 방식을 유지할 수 있을 것이라 생각합니다..! 어떻게 생각하시나요?

그렇다면 String data를 생성자 인자로 받아오는 형식으로 진행되는 게 맞을까요?

2024-06-20 02:46 UTC, KWY0218 requested changes
전체적으로 잘 반영해주신 것 같습니다! 
아래 내용 반영해주세요.

github acions 오류
아마 src/main에 application.yml을 올렸지만
현재 파일 경로는 asap-java/src/main 이라 에러가 나는 것 같습니다.
또한 빌드도 ./gradlew :asap-java:build 이런식으로 수정하면 ci 에러를 방지할 수 잇을 거 같습니다!

2024-06-20 02:46 UTC, KWY0218 commented on domain-db/src/main/kotlin/com/asap/server/domain/timeblock/TimeBlock.kt
> +    }
p1
저희 회의했을 때 기존에 존재했던 양방향 매핑을 제거하기로 했던 것으로 기억합니다..! ㅜㅜ

2024-06-20 02:46 UTC, KWY0218 commented on common/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
p2

혹시 common 모듈에 spring boot web 의존성이 들어가야 하는 이유가 있을까요..?

2024-06-20 02:46 UTC, KWY0218 commented on common/build.gradle.kts
> +    testImplementation("org.junit.jupiter:junit-jupiter")
p2

해당 의존성은 전역적으로 사용할 것 같다고 생각듭니다!
공통 의존성에 추가해주세요!

2024-06-20 02:53 UTC, sohyundoh commented on common/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
HttpStatus를 Error와 Succeed Enum class에서 가져오려면 필요합니다! 루트 gradle로 분리할까요?

2024-06-20 02:53 UTC, sohyundoh commented on domain-db/src/main/kotlin/com/asap/server/domain/timeblock/TimeBlock.kt
> +    }
앗! 넵 감사합니다 ~!!!

2024-06-20 03:25 UTC, KWY0218 commented
> 그렇다면 String data를 생성자 인자로 받아오는 형식으로 진행되는 게 맞을까요?

넵 맞습니다~! 어떻게 생각하시나요??

2024-06-20 03:26 UTC, KWY0218 commented on common/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-web")
아하 그렇군요!!!
domain-db 모듈 같은 경우에는 starter-web 의존성을 사용하지 않아서
지금 방식으로 가도 좋을 것 같습니다~!

2024-06-27 06:02 UTC, KWY0218 approved these changes
마이그레이션 홧팅 해봅시다~!

2024-06-27 06:03 UTC, merged