#295 [feat] MeetingTimeCasesStrategy 구현체 구현
ASAP-as-soon-as-possible/ASAP_Server pull request #296
Opened 2024-08-03 12:28 UTC by sohyundoh

## ✒️ 관련 이슈번호
- Closes #295 

## Key Changes 🔑
1. 알고리즘의 뼈대를 구성할 때, 가장 주가 되는 기준이 아래와 같았습니다.
- 100% - 80% 는 전체 진행시간 (H) 에서 전체 진행시간 (H-2)까지 보여주되, 2시간 이상인 회의는 H-2 > HALF인 경우만 보여준다.
이를 만족하고자, 아래와 같이 수도코드를 작성했습니다.
```
if(2시간 이상으로 진행되는 회의인 경우) {
     userCount가 80% 이상일 때 H ~ H-2(최소 한 시간)까지의 케이스를 추가
     while(userCount >= 2) {
           H ~ H-1(최소 한 시간) 까지의 케이스를 추가
           userCount--;
     }
}
else {
    while(userCount >= 2) {
         H ~ H-1 ( 최소 30분 ) 까지의 케이스를 추가
           userCount--;
     }
}
```
2. 각각 함수의 역할은 다음과 같습니다.
- `getPossibleTimeCasesOverTwoHourOverStandardRatio` : 2시간 이상 진행하는 회의에 대해 80%이상의 인원에 해당하는 회의 케이스 ( H ~ H-2까지의 케이스를 구함)
- `getPossibleTimeCasesOverTwoHourUnderStandardRatio` : 2시간 이상 진행하는 회의에 대해 80%부터 2명의 인원에 해당하는 회의 케이스 ( H ~ H-1까지의 케이스를 구함)
- `getPossibleTimeUnderTwoHour` : 2시간 미만 진행하는 회의에 대해 모든 회의 케이스를 구함
- getPossibleTimeCasesUnit은, H시간 진행하는 회의에 회의 참여자 U명이 들어왔을 때 (U, H), (U, H-30Min), .. (U-U\*0.2, H), (U-U\*0.2, H-30Min) 을 Unit으로 두고, 이 한 Unit을 구하는 함수입니다. 이 때, 2시간 이상의 회의는 진행시간 한시간 까지만 구할 수 있고, 2시간 미만의 경우 30분 까지 구할 수 있기 때문에 아래 와 같이 구분했습니다.
- `getPossibleTimeCasesUnitUnderTwoHour`
- `getPossibleTimeCasesUnitUnderTwoHour`

## To Reviewers 📢
- 2시간 미만의 회의의 경우, do while문을 사용했습니다.
- 구분해야하는 기준이 많아서 기준만 조금 다른 중복된 함수가 다소 많습니다.
- 함수명이나, 중복되는 기능을 분리할 방법이 보이신다면 조언 부탁드립니다.
- 부족한 테스트 케이스가 보이신다면 조언 부탁드립니다.
- 알고리즘이 영 별로라면 조언 부탁드립니다.

2024-08-03 15:01 UTC, KWY0218 requested changes
우선 이 정도로 리뷰 마치겠습니다!
비즈니스 로직 관련해서 상세 리뷰는 코드 리뷰 적용 이후에 진행하겠습니다!

2024-08-03 15:15 UTC, sohyundoh commented on src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
> +        final int standard = (int) (userCount * 0.2);
일전에는 매번 0.8을 계산하는 로직보다, 그 반대 비율을 빼는 방법으로 논의된 것으로 아는데 아니였을까요!

2024-08-03 15:15 UTC, sohyundoh commented on src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyTest.java
> +    class OneMemberTest {
앗 2명의 회의에서 1명을 추천하면 안되는 것이 아닌, 한 명인 경우는 묘두 추천을 하지 않는 것인가요?

2024-08-03 15:16 UTC, KWY0218 commented on src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyTest.java
> +    class OneMemberTest {
아!! 제가 실수했네요!! 굳 입니다~!

2024-08-03 15:17 UTC, sohyundoh commented on src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
> +
혹시 else문을 없애야하는 특별한 이유가 있을까요?
이후 로직에 분기문이 추가된다면 리턴문이 여러개로 퍼져있는 상황이 될 수도 있는데 이에 대해 어떻게 생각하시는지 궁금합니다!

2024-08-03 15:18 UTC, KWY0218 commented on src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
> +        final int standard = (int) (userCount * 0.2);
맞습니다!
static final a = 80 으로 설정하고,
식을 구할 때 (100-a)/100 이런 식으로 하면 어떨까 생각했습니다!
이유는 
> 비즈니스 규칙이 명시적일 것이란 생각이 드는데 어떻게 생각하시나요?

이와 같습니다 
어떻게 생각하시나요?

2024-08-03 15:19 UTC, sohyundoh commented on src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
> +        final int standard = (int) (userCount * 0.2);
아!! 너무 좋습니다! 반영하겠습니다!

2024-08-03 15:24 UTC, KWY0218 commented on src/main/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyImpl.java
> +
저는 코드 가독성을 위해 else 문을 없애려 합니다!
해당 [아티클](https://yozm.wishket.com/magazine/detail/2682/)의 early out에서 설명했듯이 저 또한 들여쓰기를 되도록 제거하도록 함으로써 코드 가독성을 높이려 하는데요!

> 로직에 분기문이 추가된다면 리턴문이 여러개로 퍼져있는 상황

저는 이러한 상황일 때, 리턴문을 상단에 올리고 이후 로직을 아래에 하는 식으로 코드를 작성합니다.
비록 if문이 여러개 생기겠지만, 저는 코드 가독성을 높이며 추후에 리팩토링에 도움이 되는 효과가 더 크다고 생각합니다!

2024-08-03 16:33 UTC, KWY0218 commented on src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyTest.java
> +            assertThat(result).isEqualTo(response);
p3
일전에 제 테스트 코드를 참고해서 작성한 것 같은데 맞을까요..?
제가 사이즈 비교를 통해 했던 것은 반환 값이 너무 많아서 편법을 쓴 것이라서.. 부끄럽네요.. 
되도록 기대값을 만들어서 size 비교가 아닌 객체 비교로 하면 좋을 것 같습니다!

또한, 저도 이전 pr에 response라고 적었지만, 의미를 더욱 명확하게 하기 위해
기대값을 response -> expected로 변경하는 것은 어떠나요??

2024-08-03 16:33 UTC, KWY0218 commented on src/test/java/com/asap/server/service/meeting/recommend/strategy/impl/MeetingTimeCasesStrategyTest.java
> +            assertThat(result).isEqualTo(response);
그리고 `assertThat(listA).isEqualsTo(listB)` 해도 알아서 값 비교를 해줍니다!

2024-08-04 02:00 UTC, KWY0218 approved these changes
코멘트 외에 별다른 수정 사항 없는 것 같습니다!
작업 고생하셨습니다!!

P4

혹시 아래 수도 코드와 같이 이런식으로 코드를 수정해보는 것은 어떠나요?
공통된 로직을 줄일 수 있다고 생각합니다..!

```
10명 3시간 기준

fun comb (toDuration, fromDuration, toUserCount, fromUserCount)
	return 조합 반환

D >= 2Hour
	for
		comb(3H, 2H 30M, 10, 8)
		comb(2H, 1H 30M, 10, 8)
		comb(2H, 1H 30M, 10, 8)
		comb(1H, 1H, 10, 8)
	for
		comb(3H, 2H 30M, 7, 5)
		comb(2H, 1H 30M, 7, 5)
		comb(2H, 1H 30M, 7, 5)
		comb(1H, 30M, 7, 5)
		comb(3H, 2H 30M, 4, 2)
		comb(2H, 1H 30M, 4, 2)
		comb(2H, 1H 30M, 4, 2)
		comb(1H, 30M, 4, 2)
```

2024-08-04 12:48 UTC, sohyundoh commented
> 코멘트 외에 별다른 수정 사항 없는 것 같습니다! 작업 고생하셨습니다!!
> 
> P4
> 
> 혹시 아래 수도 코드와 같이 이런식으로 코드를 수정해보는 것은 어떠나요? 공통된 로직을 줄일 수 있다고 생각합니다..!
> 
> ```
> 10명 3시간 기준
> 
> fun comb (toDuration, fromDuration, toUserCount, fromUserCount)
> 	return 조합 반환
> 
> D >= 2Hour
> 	for
> 		comb(3H, 2H 30M, 10, 8)
> 		comb(2H, 1H 30M, 10, 8)
> 		comb(2H, 1H 30M, 10, 8)
> 		comb(1H, 1H, 10, 8)
> 	for
> 		comb(3H, 2H 30M, 7, 5)
> 		comb(2H, 1H 30M, 7, 5)
> 		comb(2H, 1H 30M, 7, 5)
> 		comb(1H, 30M, 7, 5)
> 		comb(3H, 2H 30M, 4, 2)
> 		comb(2H, 1H 30M, 4, 2)
> 		comb(2H, 1H 30M, 4, 2)
> 		comb(1H, 30M, 4, 2)
> ```

이 combination 함수가 현재 `getPossibleTimeUnits~`와 역할이 비슷하다는 생각이 드는데 어떻게 생각하시나요!

2024-08-04 12:57 UTC, KWY0218 commented
넵 비슷하다고 생각합니다.

하지만 현재 코드에서는 각 함수별 fromDuration(HOUR 또는 HOUR_HALF)이 while문에 고정되어 있기 때문에 코드 중복이 발생하고 있다고 생각합니다.
따라서 fromDuration까지 총 4개의 매개변수를 받는다면 코드 중복을 줄일 수 있지 않을까 생각이 듭니다! 

> 함수명이나, 중복되는 기능을 분리할 방법이 보이신다면 조언 부탁드립니다.

라고 pr에 적으셔서 코멘트 남깁니다!

2024-08-04 14:35 UTC, merged